title: Tianyang Wang # name of the site
author: Wenbin Yan # name of site's author
email: tianyang.wang@etu.sorbonne-universite.fr # email of site's author
url: https://tianyangwang-su.github.io/ # root address of the site
baseurl: #"/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Welcome to the personal website of Tianyang Wang, renowned globally for his groundbreaking work in Algebraic Geometry, 
  poised to dominate the Fields Medal stage for years to come.
  — Wenbin Yan

permalink: /:slug.html

favicon: "wang_logo.jpg" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
